wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1666966676.724821
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.13.4
      8:
      - 5
